---
env: qa

server:
  uri: http://localhost:4000

services:
  auth:
    host: https://atom-api-auth.qa.learnwithatom.com
    tokenPath: /api/v1/token
    basicAuth: "NDF1Y21tdDZuZ2twMHY1bWZiaWpqbWNsc2s6MXVkMzBrYnMzdmhwb2E0YW0wN2dyNGttanU4aXBlc3Nvb3Rib2xnNnEzMTAyMnRhdXI1Mg=="

  adminApi:
    host: https://atom-api-admin.qa.learnwithatom.com
    path: /admin/v1/proctoru/webhook  

  proctorU:
    secret: "4ad5577f-06b3-46d1-87e0-cfd0676e6f53"
    webhookPath: /proctoru/webhooks    
